version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: roles
      MYSQL_ROOT_PASSWORD: "123456"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - web

networks:
  web:
    external: true
